- hosts: all
  gather_facts: True
  vars:
    sqldbendpoint: tmpgod8y7mpm8w.cyqqy0awrrdo.eu-central-1.rds.amazonaws.com
  tasks:
    - name: Load test data to DB
      shell: cat mysqlsampledatabase.sql | mysql -uphpuser -pphpuserPHPUSER90 -h {{ sqldbendpoint }}

